"""add_body_html

Revision ID: 13417aa5ed5c
Revises: 8be35fd955b0
Create Date: 2017-06-29 09:19:22.650614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13417aa5ed5c'
down_revision = '8be35fd955b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('haha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'posts', 'body_html')
    op.drop_table('haha')
    # ### end Alembic commands ###
