"""add img

Revision ID: 5d2794a51fa8
Revises: 257bed91462a
Create Date: 2017-07-05 20:41:51.250059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2794a51fa8'
down_revision = '257bed91462a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('img', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'img')
    # ### end Alembic commands ###
